name: Linter Check

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: â¬‡ï¸ Cloner le repository
        uses: actions/checkout@v4

      - name: ğŸ“¦ Installer les dÃ©pendances
        run: npm install

      - name: ğŸ” ExÃ©cuter le linter
        run: scripts/pre-commit.sh
